# Repos
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:WPMedia/Podspecs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'WPObjectMapperExample' do
  pod 'WPObjectMapper', :inhibit_warnings => false, :path => '..'
  pod 'WPFaker', '~> 0.2.0'

  target 'WPObjectMapperExampleTests' do
    pod 'WPFaker', '~> 0.2.0'
  end
end

